sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- pip install coveralls
script:
- py.test tests.py
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: BXeuKSz9T27/GVpA+VmcFzZ1bX0nWTZeJzVUa7+UlvZWcIKyWxpH1CL3ZpGdZJviU7P5f/vBxPfWgO5gnMs3fKUIGJSQS3nhxLf1UwgkqQm1BSxlHmLEASvWR3D7U3+dsumIg2J8MCQh/E6aUGRn+1zUJscYAHXDsYn5x5ASaTp7e6wLRj/OfgrqFtAMR6Wp7qoW+CjvyA03srBScylmJhDizsBWtwFBA4nue0gLGXSzdqZHH5eGuA6lmgCaCl0u+4cVhur9AAAGWFPcQMh6bBPzCZ/zL7Y9HzTK5CaVmcKhmmhw4sSfNmxgir8X7vNIxpS9NSVj2TQDltmvVxRLFYZyQjuWaRmCYPektMvDThK15eMH2lkfS72s6xzowT1sSvlCgTsE06igoxd0k8cFPvgoG7+qyVsjf4P3zILL0KHDoHtsBfv6NpyFekIlftOTTbsCbE0cX2sd8bvfhz5iVqtJFUFhf4NA1QhCqGb1fFuqohTEtKRwQu//i0CvmB9vqXlUG1rO1gCch8PPBmEC+p46aeHWtGkQTsPIecE+2QH/2sFBfYdaXh5ARzsTOVrEcd2Zy8hCbLM2hxS0PvnkFiilm0wbVqnx9buUk9IEU/imNmuJ5+4DNEqPqhhD/wZ1j9bUdlG7W1gMMbvpNDQW4i4Ifgjfp/Dg5PWPJMVTen8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/flux_led
