sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- pip install coveralls
script:
- py.test tests.py
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: Nker0KEJNSx3+EJUVaz/Em6aon9M9RITP5CnMSFqtQqN3gFQrYDLX29UAJEz37lTu2z5oQRtg1ki6uOu9kosI5UIdCTkyybYM8bLpEsRUbGcbdKHEGLTswIrxEO4UW7C+Xlfv9/g8RUfEnVHAkbAs6YhDFEvrQ8p37NOTl4otM2tlZ8JnZiIYH2TwUa7iOwU3HcuOIuWyx0vABVxUz+SSf2c1snrnvdAhqpHV0NbziLqJPzQOdLQb2hVUzdNa6weRZP+o+NcfuH/Axv3XsVKhPOkyIyO4oMXMXiYV5fdQ5O6xs3CRyGzxZy5qaFVaFWksJzjGMpGCgxK5TUvEz2fNNkQ7XSKJZJX1wK/t5zVJq82ZedHIB7PMxgIAoHkYEoFi7p/daJMqTry0F0gjXokELx+Ad5S9EJ86NcUmF00KaxfSW7s9RdtIVqw8M9Eck15SnpBom6gsqDqiRdHWwOjmGomR3UiWsiPkWi0YIBYmXloIHiHYMKVmi8cM+Nbh/G9Q3H8MiJ4p1GoiiapGiq3mvJ1ewxoymwdanK/h/XeroPzWumQ2C16WPm7uIsnKzlpmEcI/qB3FoPP+pM3zA3NSzShfaPMSe0OIB75drnapOcsnt6PB4FMakcMfUKM365BZSApNo+7FEYwUpwob5OIq8S99rkrH2Dv8tOeBLvWa6A=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/flux_led
